### ISSUE TITLE
Mobile friendly "Sift" view

### ISSUE THREAD

**Issue by rhodey** [radiowitness/radiowitness.io#12]
The Radio Witness web app only has a couple different pages/views right now:

+ Cities (home)
+ About
+ Timeseries (query range select)
+ Sift (the candy-crush looking view with hotkeys)
+ Private Topics
+ Published Topic

All of these views function well enough and look pretty alright on mobile except for "Sift". The Sift view is a very large part of the web app and relies heavily on hotkeys. **When viewed on mobile Sift appears to do nothing at all, this is very bad.**

I don't believe that serious analysis of call events is possible using a smartphone, or at least it will be a lot of work to make a fully-functional mobile friendly version of Sift. Instead our goal in the short term should be to make Sift do something simple on mobile.

**Comment by rhodey** [comment]
For the purpose of [our first milestone](https://github.com/radiowitness/radiowitness.io/milestone/1) this issue will be considered fixed if we accomplish the following:

- [ ] on mobile: remove all hotkey features
- [ ] on mobile: render the call event colored bubbles to take up the full width of the screen
- [ ] on mobile: let users scroll through a list of call event colored bubbles
- [ ] on mobile: play & pause call audio when users tap on a call event colored bubble

**Comment by FelixBl** [comment]
A tablet sized device might be an interesting medium to analyze calls.

**Comment by FelixBl** [comment]
> render the call event colored bubbles to take up the full width of the screen
Why not let css/ bootstrap render the call boxes. Using the framework would automatically scale the bubbles to mobile devices.

**Comment by rhodey** [comment]
^^ lets do it :+1: :+1: :+1:

**Comment by rhodey** [comment]
closed by #19
