### ISSUE TITLE
Create Help / Description For Features

### ISSUE THREAD

**Issue by FelixBl** [radiowitness/radiowitness.io#7]
Currently, it is very unintuitive, what a "Private Topic" is, what it is used for.
Buttons like the "Publish" button have not description. I do not know what happens once I clicked this guy.

It would be awesome to have some (context sensitive) help, that explains what one can do on an individual page.

This way, the probability of users trying out features increases since they are not lost on a blank page that offers awesome "hidden" features.

**Comment by rhodey** [comment]
closed by #19
